[[quote]]
japanese = "逃げちゃダメだ"
translation = "You mustn't run away."
romaji = "Nigeccha dame da"
source = "Neon Genesis Evangelion"

[[quote]]
japanese = "人は心で生きるんだ"
translation = "People live by their hearts."
romaji = "Hito wa kokoro de ikiru nda"
source = "Your Name"

[[quote]]
japanese = "諦めたらそこで試合終了だよ"
translation = "If you give up, the game is over."
romaji = "Akirametara soko de shiai shūryō da yo"
source = "Slam Dunk"

[[quote]]
japanese = "人はいつ死ぬと思う？心の中で誰かに忘れられたときさ"
translation = "Do you know when people die? When they are forgotten in someone’s heart."
romaji = "Hito wa itsu shinu to omou? Kokoro no naka de dareka ni wasurerareta toki sa"
source = "One Piece"

[[quote]]
japanese = "心を燃やせ"
translation = "Set your heart ablaze."
romaji = "Kokoro o moyase"
source = "Tengen Toppa Gurren Lagann"

[[quote]]
japanese = "道は自分で切り開くものだ"
translation = "You carve your own path."
romaji = "Michi wa jibun de kirihiraku mono da"
source = "Naruto"

[[quote]]
japanese = "命より大事なものなんてない"
translation = "There’s nothing more important than life."
romaji = "Inochi yori daiji na mono nante nai"
source = "Fullmetal Alchemist"

[[quote]]
japanese = "俺の辞書に不可能はない"
translation = "Impossible doesn’t exist in my dictionary."
romaji = "Ore no jisho ni fukanō wa nai"
source = "One Piece"

[[quote]]
japanese = "人は信じたいものを信じる"
translation = "People believe what they want to believe."
romaji = "Hito wa shinjitai mono o shinjiru"
source = "Death Note"

[[quote]]
japanese = "夢を諦めるな"
translation = "Never give up on your dreams."
romaji = "Yume o akirameru na"
source = "Fairy Tail"

[[quote]]
japanese = "本当の強さとは優しさだ"
translation = "True strength is kindness."
romaji = "Hontō no tsuyosa to wa yasashisa da"
source = "Attack on Titan"

[[quote]]
japanese = "恐れずに進め"
translation = "Move forward without fear."
romaji = "Osorezu ni susume"
source = "My Hero Academia"

[[quote]]
japanese = "生きるってことは戦うことだ"
translation = "To live is to fight."
romaji = "Ikiru tte koto wa tatakau koto da"
source = "Bleach"
