[[quote]]
japanese = "古池や\n蛙飛び込む\n水の音"
translation = "An old pond —\nA frog jumps in —\nThe sound of water."
source = "Matsuo Bashō"

[[quote]]
japanese = "夏草や\n兵どもが\n夢の跡"
translation = "Summer grasses—\nAll that remains\nOf warriors' dreams."
source = "Matsuo Bashō"

[[quote]]
japanese = "静けさや\n岩にしみ入る\n蝉の声"
translation = "Such stillness—\nThe cicadas' cries\nSink into the rocks."
source = "Matsuo Bashō"

[[quote]]
japanese = "春の海\nひねもすのたり\nのたりかな"
translation = "Spring sea—\nAll day long\nWaves roll gently."
source = "Matsuo Bashō"

[[quote]]
japanese = "秋深き\n隣は何を\nする人ぞ"
translation = "Deep autumn—\nWho lives next door\nAnd what do they do?"
source = "Matsuo Bashō"

[[quote]]
japanese = "冬ざれや\nかなしき鳥の\n声する"
translation = "Winter desolation—\nThe sad voice\nOf a bird."
source = "Matsuo Bashō"

[[quote]]
japanese = "夏の夜や\n蛍の光\n消えたり"
translation = "Summer night—\nThe glow of fireflies\nFades away."
source = "Matsuo Bashō"

[[quote]]
japanese = "花の雲\n鐘は上野か\n浅草か"
translation = "Clouds of blossoms—\nIs that bell from Ueno?\nOr from Asakusa?"
source = "Matsuo Bashō"

[[quote]]
japanese = "春雨や\n川面を濡らす\n小舟かな"
translation = "Spring rain—\nIt wets the river’s surface,\nA little boat floats."
source = "Matsuo Bashō"

[[quote]]
japanese = "朝顔に\nつるべ取られて\nもらい水"
translation = "Morning glory—\nMy well bucket was taken,\nGot water from neighbor."
source = "Kobayashi Issa"

[[quote]]
japanese = "名月や\n池をめぐりて\n夜もすがら"
translation = "Bright moon—\nAround the pond\nAll night long."
source = "Matsuo Bashō"

[[quote]]
japanese = "夏草や\n武士どもが\n夢の跡"
translation = "Summer grasses—\nAll that remains\nOf warriors’ dreams."
source = "Matsuo Bashō"

[[quote]]
japanese = "春の山\n霞たなびく\n花の声"
translation = "Spring mountains—\nMist floats by,\nVoices of flowers."
source = "Matsuo Bashō"
