[[quote]]
japanese = "七転び八起き"
translation = "Fall down seven times, stand up eight."
source = "Japanese proverb"

[[quote]]
japanese = "一期一会"
translation = "Once in a lifetime encounter."
source = "Japanese proverb"
