[[quote]]
japanese = "七転び八起き"
translation = "Fall down seven times, stand up eight."
source = "Japanese proverb"

[[quote]]
japanese = "一期一会"
translation = "Once in a lifetime encounter."
source = "Japanese proverb"

[[quote]]
japanese = "猿も木から落ちる"
translation = "Even monkeys fall from trees."
source = "Japanese proverb"

[[quote]]
japanese = "雨降って地固まる"
translation = "After the rain, the ground hardens."
source = "Japanese proverb"

[[quote]]
japanese = "石の上にも三年"
translation = "Three years on a stone—perseverance pays off."
source = "Japanese proverb"

[[quote]]
japanese = "花より団子"
translation = "Dumplings over flowers—practicality over aesthetics."
source = "Japanese proverb"

[[quote]]
japanese = "二兎を追う者は一兎をも得ず"
translation = "Chase two rabbits, catch none."
source = "Japanese proverb"

[[quote]]
japanese = "猫に小判"
translation = "Gold coins to a cat—wasting something on someone who can't value it."
source = "Japanese proverb"

[[quote]]
japanese = "馬の耳に念仏"
translation = "Buddhist prayers in a horse’s ear—preaching to deaf ears."
source = "Japanese proverb"

[[quote]]
japanese = "虎穴に入らずんば虎子を得ず"
translation = "You cannot get a tiger cub without entering the tiger’s cave."
source = "Japanese proverb"

[[quote]]
japanese = "口は災いの元"
translation = "The mouth is the source of misfortune."
source = "Japanese proverb"

[[quote]]
japanese = "井の中の蛙大海を知らず"
translation = "A frog in a well does not know the ocean."
source = "Japanese proverb"

[[quote]]
japanese = "魚心あれば水心"
translation = "If the fish is willing, so is the water—mutual feelings matter."
source = "Japanese proverb"

[[quote]]
japanese = "覆水盆に返らず"
translation = "Spilt water will not return to the tray—what’s done is done."
source = "Japanese proverb"

[[quote]]
japanese = "人生は短い、ケツを食べて"
translation = "The way of the master is pain ."
source = "Japanese proverb"
