name: Release

on:
  push:
    tags:
      - "v*"   # Runs when you push a version tag like v0.2.7

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-gnu,
          x86_64-apple-darwin,
          aarch64-apple-darwin,
          x86_64-pc-windows-msvc
        ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Package binary
        run: |
          BIN_NAME=kotofetch
          VERSION=${GITHUB_REF#refs/tags/}
          TARGET=${{ matrix.target }}
          OUT_DIR=release/$TARGET
          mkdir -p $OUT_DIR

          if [[ "$TARGET" == *windows* ]]; then
            cp target/$TARGET/release/$BIN_NAME.exe $OUT_DIR/
            cd release && zip -r ${BIN_NAME}-${VERSION}-${TARGET}.zip $TARGET
          else
            cp target/$TARGET/release/$BIN_NAME $OUT_DIR/
            cd release && tar czf ${BIN_NAME}-${VERSION}-${TARGET}.tar.gz $TARGET
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotofetch-${{ matrix.target }}
          path: release/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
